### PR TITLE
Update rapportive.py

### PR DESCRIPTION
**Pull request by muloka**
Added error checking to the request function.

### CODE REVIEW

**Comment by Nateliason** [comment]
Looks like you found it before I could respond! I'm using the same fix right now.

**Comment by jordan-wright** [comment]
Let me take a look at this later this evening, and I'll merge if everything checks out.

For now, could you PEP8 the commit so that it passes the Travis CI build?

Thanks for working on this!

**Comment by muloka** [comment]
Done and you're most welcome.

**Comment by jordan-wright** [comment]
Looks like this should work just fine. At first, I was worried that, by returning an error instead of a Profile there might be an error, but I don't think this will be an issue (I'll verify later). Eventually it might be best to throw an error instead of returning one.

**Pull request merged**
