### PR TITLE
Refactor rapportive, add setup.py

### PR DESCRIPTION
**Pull request by hughdbrown**
rapportive.py
- Change argument parsing library
- Clean up imports
- Create object for profile
- move to rapportive/

Infrastructure
- Add setup.py
- Add scriptfile
- Add rapportive/version.py
- Add rapportive/**init**
- Add requirements.pip

pep8 fixes

### CODE REVIEW

**Comment by jordan-wright** [comment]
I may be missing something, but I'm not entirely sure as to the purpose of rapportive_cmd... Why not just call rapportive.py directly?

Thanks for taking the time to look into rapportive.py. I started it as a simple script - I guess it is about time to make it a more robust library.

**Comment by hughdbrown** [comment]
`scripts/rapportive_cmd` is a simple way to make the script globally accessible. 

http://stackoverflow.com/questions/874521/python-install-script-to-system

I've come to think it is a good practice since I have had to run in more complex environments -- scripts called by cron jobs, scripts inside virtual environments, scripts deployed in rpms, etc.

Also, it plays nicely with `python setup.py install --user`.

It might be more natural if the script were renamed `rapportive` instead of `rapportive_cmd`.

**Comment by hughdbrown** [comment]
So in addition to a `setup.py`, I am providing:
- skeleton `.travis.yml` file for builds
- script installation
- pep8 and pylint testing
- `requirements.pip` for a clear statement of what needs to be installed
- change to use `docopt` argument parsing (see video here: http://docopt.org/ )

**Comment by jordan-wright** [comment]
I have merged the branch. I appreciate all your hard work - I have not messed around with all the travis builds, pylint, etc., so I will be reviewing these changes to learn! 

Thanks again.

**Comment by hughdbrown** [comment]
Don't forget to modify the travis reference to point to your own build status. Currently, it uses `travis-ci/hughdbrown/rapportive.png` instead of `travis-ci/jordan-wright/rapportive.png`.

**Comment by jordan-wright** [comment]
Done and done! Thanks again for your help.

**Pull request closed without merging**
